### ISSUE TITLE
okHttp Error

### ISSUE THREAD

**Issue by AlvaroMenezes** [amplitude/Amplitude-Flutter#134] opened 2022-12-01 05:02 UTC
## Expected Behavior
Not show error or throws exception

## Current Behavior
W/OkHttp  ( 3743): unable to load android socket classes
W/OkHttp  ( 3743): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  ( 3743):      at java.lang.Class.getMethod(Class.java:2072)
W/OkHttp  ( 3743):      at java.lang.Class.getDeclaredMethod(Class.java:2050)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  ( 3743):      at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  ( 3743):      at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  ( 3743):      at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
W/OkHttp  ( 3743):      at com.amplitude.api.AmplitudeClient.$r8$lambda$uWBdBgn9ebx5ZjaSsGzJj44YwX4(Unknown Source:2)
W/OkHttp  ( 3743):      at com.amplitude.api.AmplitudeClient$$ExternalSyntheticLambda0.get(Unknown Source:0)
W/OkHttp  ( 3743):      at com.amplitude.util.DoubleCheck.get(DoubleCheck.java:28)
W/OkHttp  ( 3743):      at com.amplitude.api.AmplitudeClient.lambda$null$0(AmplitudeClient.java:368)
W/OkHttp  ( 3743):      at com.amplitude.api.AmplitudeClient$$ExternalSyntheticLambda3.newCall(Unknown Source:2)
W/OkHttp  ( 3743):      at com.amplitude.api.AmplitudeClient.makeEventUploadPostRequest(AmplitudeClient.java:2272)
W/OkHttp  ( 3743):      at com.amplitude.api.AmplitudeClient$12.run(AmplitudeClient.java:2137)
W/OkHttp  ( 3743):      at android.os.Handler.handleCallback(Handler.java:938)
W/OkHttp  ( 3743):      at android.os.Handler.dispatchMessage(Handler.java:99)
W/OkHttp  ( 3743):      at android.os.Looper.loop(Looper.java:250)
W/OkHttp  ( 3743):      at android.os.HandlerThread.run(HandlerThread.java:67)

## Steps to Reproduce
1. final _amplitude = Amplitude.getInstance(instanceName: "xpto");
2. await _amplitude.init(apiKey);
3.await _amplitude.enableCoppaControl();
4.await _amplitude.trackingSessionEvents(true);
5.await _amplitude.setUserId(user);
untill here all ok, next step show error on terminal
6. await _amplitude.logEvent(eventType, eventProperties: eventProperties); 
7. await _amplitude.uploadEvents();

## Environment
- SDK Version: ^3.12.0
- Flutter Version: 3.3.9
- Device: Motorola moto g(9) plus
- Device OS and Version:  Android 11 Version 1.4.3

**Comment by qingzhuozhen** [comment] 2022-12-02 01:31
Hi @AlvaroMenezes, I guess this is a duplicate of https://github.com/amplitude/Amplitude-Flutter/issues/58, you can alleviate this by upgrade the okhttp library version

**Closed as completed** 2022-12-05 06:44 UTC
Labels: bug
