### ISSUE TITLE
Access hidden method error

### ISSUE THREAD

**Issue by andim27** [amplitude/Amplitude-Flutter#178] opened 2024-03-07 15:34 UTC
Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (max-target-q,core-platform-api, reflection, denied)
W/OkHttp  (24066): unable to load android socket classes
W/OkHttp  (24066): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  (24066):      at java.lang.Class.getMethod(Class.java:2937)
W/OkHttp  (24066):      at java.lang.Class.getDeclaredMethod(Class.java:2914)
W/OkHttp  (24066):      at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  (24066):      at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  (24066):      at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  (24066):      at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  (24066):      at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  (24066):      at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  (24066):      at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  (24066):      at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  (24066):      at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  (24066):      at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  (24066):      at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
W/OkHttp  (24066):      at com.amplitude.api.AmplitudeClient.$r8$lambda$uWBdBgn9ebx5ZjaSsGzJj44YwX4(Unknown Source:2)
W/OkHttp  (24066):      at com.amplitude.api.AmplitudeClient$$ExternalSyntheticLambda1.get(Unknown Source:0)
W/OkHttp  (24066):      at com.amplitude.util.DoubleCheck.get(DoubleCheck.java:28)
W/OkHttp  (24066):      at com.amplitude.api.AmplitudeClient.lambda$null$0(AmplitudeClient.java:368)
W/OkHttp  (24066):      at com.amplitude.api.AmplitudeClient$$ExternalSyntheticLambda2.newCall(Unknown Source:2)
W/OkHttp  (24066):      at com.amplitude.api.AmplitudeClient.makeEventUploadPostRequest(AmplitudeClient.java:2305)
W/OkHttp  (24066):      at com.amplitude.api.AmplitudeClient$12.run(AmplitudeClient.java:2188)
W/OkHttp  (24066):      at android.os.Handler.handleCallback(Handler.java:958)
W/OkHttp  (24066):      at android.os.Handler.dispatchMessage(Handler.java:99)
W/OkHttp  (24066):      at android.os.Looper.loopOnce(Looper.java:205)
W/OkHttp  (24066):      at android.os.Looper.loop(Looper.java:294)
W/OkHttp  (24066):      at android.os.HandlerThread.run(HandlerThread.java:67)
Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (unsupported,core-platform-api, reflection, allowed)
Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (unsupported,core-platform-api, reflection, allowed)
 Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (unsupported,core-platform-api, reflection, allowed)
D/TrafficStats(24066): tagSocket(154) with statsTag=0xffffffff, statsUid=-1

## Environment
- Flutter Version:  3.20.0-1.2.pre
- amplitude_flutter: ^3.16.2
- Device: Android 13
- Device OS and Version:  Android 13

**Comment by Mercy811** [comment] 2024-03-15 23:20
Hi @andim27, Amplitude Flutter SDK v3.x wraps Amplitude maintenance Android SDK. The error seems to be caused by an old version of okhttp in Amplitude maintenance Android SDK which is in end-of-support phase. Learn more about [Amplitude SDKs and Tools Maintenance & Support Policy](https://www.docs.developers.amplitude.com/data/sdks/sdk-maintenance-and-support/). 

We are updating the Flutter SDK to wrap on the latest Android and iOS SDKs. [amplitude_flutter: 4.0.0-beta.1](https://pub.dev/packages/amplitude_flutter/versions/4.0.0-beta.1) is released as a beta version. Here is the [migration guide](https://www.docs.developers.amplitude.com/data/sdks/flutter/migration/). I will have a full reference doc soon. Migrating to v4.x should solve this problem.

**Closed as completed** 2024-03-21 22:29 UTC
Labels: bug
