### ISSUE TITLE
Upgrade kotlin_version to 1.3.40 and higher

### ISSUE THREAD

**Issue by kalyujniy** [amplitude/Amplitude-Flutter#67] opened 2021-09-22 08:12 UTC
## Current Behavior
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':amplitude_flutter' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21

## Steps to Reproduce
Add plugin to project and start it

## Environment
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80 darwin-arm, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)

- Device:  all Android
- Device OS and Version: all Android

**Comment by PieterAelse** [comment] 2021-09-22 09:13
I'm having the same issue!

**Comment by yuhao900914** [comment] 2021-09-27 18:29
This has been fixed in amplitude_flutter 3.4.0. Thanks.

**Closed as completed by yuhao900914** 2021-09-27 18:29 UTC
Labels: bug

**Comment by kirillwebmail** [comment] 2021-10-01 07:45
After update plugin in debug mode all works fine, but when i build release app crashed with this error

Caused by: android.view.InflateException: Binary XML file line #11 in com.android.chrome:layout/0_resource_name_obfuscated: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1231)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at ED1.a(chromium-TrichromeChromeGoogle.aab-stable-460606133:3)
        at Cl4.b(chromium-TrichromeChromeGoogle.aab-stable-460606133:7)
        at jn0.run(chromium-TrichromeChromeGoogle.aab-stable-460606133:4)
        at LN.run(chromium-TrichromeChromeGoogle.aab-stable-460606133:10)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Caused by: java.lang.IllegalArgumentException: ChromeColors requires a value for the com.android.chrome:attr/0_resource_name_obfuscated attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
        at PQ1.c(chromium-TrichromeChromeGoogle.aab-stable-460606133:5)
        at HV.b(chromium-TrichromeChromeGoogle.aab-stable-460606133:3)
        at org.chromium.chrome.browser.compositor.CompositorView.g(chromium-TrichromeChromeGoogle.aab-stable-460606133:4)
        at org.chromium.chrome.browser.compositor.CompositorView.<init>(chromium-TrichromeChromeGoogle.aab-stable-460606133:5)
        at org.chromium.chrome.browser.compositor.CompositorViewHolder.<init>(chromium-TrichromeChromeGoogle.aab-stable-460606133:15)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:854) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1231) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at ED1.a(chromium-TrichromeChromeGoogle.aab-stable-460606133:3) 
        at Cl4.b(chromium-TrichromeChromeGoogle.aab-stable-460606133:7) 
        at jn0.run(chromium-TrichromeChromeGoogle.aab-stable-460606133:4) 
        at LN.run(chromium-TrichromeChromeGoogle.aab-stable-460606133:10) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:336) 
        at android.os.Looper.loop(Looper.java:174) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2021-10-01 09:18:47.948 13380-13380/? E/ocessService0:: Not starting debugger since process cannot load the jdwp agent.
2021-10-01 09:18:58.459 4461-12883/? E/memtrack: Couldn't load memtrack module
2021-10-01 09:19:31.825 2060-7208/? E/memtrack: Couldn't load memtrack module

when i remove amplitude plugin and build app all works fine

**Comment by jgadjetx** [comment] 2022-10-16 01:10
I'm getting this error right now:

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':amplitude_flutter' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.40

**Comment by yuhao900914** [comment] 2022-10-21 07:21
Hi @jgadjetx, 
What's your gradle version and android gradle version?
